### ISSUE TITLE
Path parameters cannot contain / or \

### ISSUE THREAD

**Issue by hbusul** [GAMS-dev/engine-ui#9]
While trying to upload a model if model name contains `/` or `\`,  `POST namespaces/{namespace}/{model}` gives 404 as `model` contains `/`. Instead of trying to make this request, the UI should warn the user as model names cannot contain `/`.

- Creating a namespace `POST namespaces/{namespace}`
- Creating a model `POST namespaces/{namespace}/{model}`

**Comment by fproske** [comment]
@hbusul I now properly encode user-controlled parts of URIs. However, I still can't use a forward slash`/` in a namespace name (probably model name as well). This seems to be an issue with the backend parser. Can you look into this? I guess the easiest solution would be to not allow `/`. I guess that a reasonable restriction to have.

**Comment by fproske** [comment]
We no longer allow forward slashes in namespace names. This can be closed..
